### ISSUE TITLE
Option to reverse behavior and make moving all endpoints default without holding Alt.

### ISSUE THREAD

**Issue by apoapostolov** [Reaver01/mwpm#1]
Can we have an option to not need ALT to move all connected points, or a reverse of the current situation where ALT is needed only to move individual point but without it all endpoints are moved.

It is a bit hard to get how to use ALT (not when moving the endpoint but while an endpoint is moved) otherwise you move all the walls. It also is often the case where you want to move all connected endpoints together, and should be optionally a way to make this the default.

**Comment by Reaver01** [comment]
Will make this an option in settings.

**Comment by Reaver01** [comment]
This is a setting now in 0.3.0
