### ISSUE TITLE
Improvement: Add ability to move all endpoints at same location

### ISSUE THREAD

**Issue by trev33b** [Reaver01/mwpm#3]
Suggested improvement: If the user holds down the Shift key (or some other modifier available for use), then move all of the endpoints that share the same location.  This can allow the user to fine tune the walls/shapes they are creating with a single drag instead of one per endpoint that shares the same location.

As a side note, I really like the auto-delete of short walls.

**Comment by Reaver01** [comment]
This is literally what the module does...

**Comment by trev33b** [comment]
No.  When I hold down the alt key and drag an end-point, all lines connected to that end-point are moved through the whole chain of connected lines.  That's not what I want.

**Comment by trev33b** [comment]
Example:

1            2
 o-----o
 |          |
 o-----o
3           4

If I drag point 1 in the diagram above with the Alt key held down, all points are moved.  I only want to move point 1.

(Note 2 should be connected to 4, looks ike white space was removed)

**Comment by Reaver01** [comment]
You're going to have to post a gif or something because I have no idea what you mean.

**Comment by trev33b** [comment]
Sorry, took me a while to get back to this, but now that I'm building walls again I took another look at this.  I learned a few new things and wanted to close the loop on this.

I figured out that what was causing me problems was not understanding the selection mechanism.  I still haven't learned how to create an animate gif, but here's an ASCII pic that we can use as the basis:

A------B------C------D

If you click on a wall end point with no key-modifiers, a segment is selected and then if you use the Alt key while dragging the end point, you can move it wherever you want and all segments that shared that end point will have their end point updated to match, which is exactly how your feature is intended to work.

So, using the pic above, if I select B and then drag it somewhere else while holding down Alt, segments AB and BC get updated for the new position of B.  So far so good.

What was not obvious to me was that if I selected an end point WHILE holding the Alt key, the entire set of walls (ABCD) gets selected and even if I hold down Alt while dragging them, the entire set of ABCD gets moved.

Once I figured out I have to select things and hit keys in the right order, everything is fine.

Anyway, I don't think you need to do anything to change this.  I just wanted to communicate what I was seeing / learned.  I do think there's an occasional benefit to moving the entire ABCD set of segments, but now that I know the right incantation for moving just B, I'm good.
