### ISSUE TITLE
0.8.1 compatibility

### ISSUE THREAD

**Issue by Sk1mble** [Reaver01/mwpm#4]
Hello! I love this module; it's one of the few that're indispensible to me. I've been updating my system to be compatible with Foundry 0.8.1 and I've also made some tweaks to MWPM to make it work, too. Let me know if you'd like the edited version.

The changes mostly relate to changes to the hook parameters.

**Comment by Reaver01** [comment]
If you have already done this please make a pull request and I can get a version published with those changes! I have unfortunately not been in the mood to keep up with personal projects with my actual job being so busy lately. Pull request will make sure you get the credit on the repo for the changes :)

**Comment by Sk1mble** [comment]
No problem, I have done that!
